name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # Cho phép kích hoạt thủ công

jobs:
  build:
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: "UTF-8"

    strategy:
      matrix:
        python-version: [3.12]

    permissions:
      actions: write
      contents: write

    steps:
      - name: Configure git
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "110257560+BnanZ0@users.noreply.github.com"
          git config --global user.name "RU"

      - uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          Get-ChildItem -Path ".\tests\*.py" | ForEach-Object {
              Write-Host "Running tests in $($_.FullName)"
              python -m unittest $_.FullName
          }

      - name: Check release version
        id: release-version
        shell: pwsh
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          $tag = $env:REF_NAME
          $isRelease = $tag -match '^v?\d+\.\d+\.\d+$'
          if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") { $isRelease = $true }
          "is_release=$($isRelease.ToString().ToLowerInvariant())" >> $env:GITHUB_OUTPUT
          Write-Host "Release version: $isRelease"

      - name: Build with PyAppify Action
        if: steps.release-version.outputs.is_release == 'true'
        id: build-app
        uses: ok-oldking/pyappify-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_exe_only: true # Chỉ đóng gói exe, không tạo file update

      - name: Release
        uses: softprops/action-gh-release@v3
        if: steps.release-version.outputs.is_release == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "Custom Global Build without Auto-Update components"
          draft: false
          prerelease: false
          make_latest: true
          files: pyappify_dist/*
